server:
  port: 8093
spring:
  application:
    name: spring-boot-mongodb
#  data:
#    mongodb:
#      uri: mongodb://8.129.213.16:27017/backup

# uri=mongodb://name:pass@localhost:27017/dbname:
# https://www.jianshu.com/p/d86a726be84a

  datasource:
    url: jdbc:mysql://192.168.31.133:3306/gn-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: gwk_632697105qq
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
